version: '3'

services:

  library_db:
    image: "postgres"
    container_name: library_db
    restart: always
    network_mode: bridge
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=library_postgres_db
      - PGDATA=/var/lib/postgresql/data/pgdata
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 60s
      retries: 5
    networks:
      - library_network

  library_manager:
    build: ./
    container_name: library_manager
    links:
      - library_db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://library_db:5432/library_postgres_db?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    networks:
      - library_network
    ports:
      - "8080:8080"
    depends_on:
      library_db:
        condition: service_healthy


volumes:
  pgdata:

networks:
  library_network:
    driver: bridge