app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/library_postgres_db
    username: postgres
    password: password
    pool-size: 30
#  spring:
#    data:
#      rest:
#        base-path: '/api'
