app:
  datasource:
    jdbc-url: jdbc:postgresql://library_db/library_postgres_db
    username: postgres
    password: postgres
    pool-size: 30
#  spring:
#    data:
#      rest:
#        base-path: '/api'
